# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Preguntas
    url: preguntas/
    weight: 20
  - name: Mundo Topia
    url: mundotopia/
    weight: 30
  - name: Test de personalidad
    parent: mundotopia
    url: trivia/
    weight: 40
