# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day:
  theme_night: minimal
  font: native
  font_size: L

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'Una isla misteriosa, personajes entrañables, y una idea revolucionaria. Topia es una novela para leer y releer, un caleidoscopio de vivencias que permite al lector habitarla y dejarse habitar. Un libro que sigue la tradición de Tomás Moro, y el Shangri La de Hilton, pero desde una perspectiva actual, femenina y que invita a la acción más que a la contemplación.'
    twitter: 'felipes88'
  analytics:
    google_analytics: ''
    baidu_tongji: ''
  verification:
    google: ''
    baidu: ''

# Site header

header:
  navbar:
    enable: false
    align: r
    show_logo: false
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: false

#footer:
#  copyright:
#    notice: '© {year} Me. This work is licensed under {license}'
#    license:
#      enable: true
#      allow_derivatives: false
#      share_alike: true
#      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features

features:
  syntax_highlighter:
    enable: false
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/<username>/<repository>'
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: ''
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: ''
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false
